webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/public/build'
    # If multiple builds are defined (as shown below), you can disable the default build:
    # output_path: false

    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true
        'data-turbo-track': reload
    link_attributes:
        # Uncomment if using Turbo Drive
        'data-turbo-track': reload

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'